apiVersion: v1
kind: Service
metadata:
  name: lab06apictacte
  labels:
    app: lab06apictacte
spec:
  ports:
    - name: mocks
      port: 7071
      targetPort: 7071
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: lab06apictacte
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab06apictactebus
spec:
  selector:
    matchLabels:
      app: lab06apictacte
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: lab06apictacte
    spec:
      containers:
        - name: lab06apictacte
          image: mzegarra/lab06busctacte:0.0.2
          imagePullPolicy: IfNotPresent #Always       
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8080
            - containerPort: 7071
