apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    app: envars
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
      - name: URL_WS_VAR
        valueFrom:
          configMapKeyRef:
            name: app-config-01
            key: URL_WS
      - name: USER_VAR
        valueFrom:
          configMapKeyRef:
            name: app-config-01
            key: USER