apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lab06apictacte
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lab06apictacte
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
