apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    app: envars
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: URL_WS
      value: "http://www.demo.com"
    - name: USER
      value: "admin"
    - name: PWD
      value: "password"      