version: '3.8'
services:
  website:
    image: "web01:latest"
    build:
      context: angular/
      dockerfile: ./Dockerfile
    ports:
      - 8081:80
  website02:
    image: "web01:latest"
    build:
      context: angular/
      dockerfile: ./Dockerfile
    ports:
      - 8081:80      